site_name: VampireXRAY Blog
site_description: Just My Articles
site_author: ReemKhalid
site_url: https://x-ray2004.github.io/My-Blog/

theme:
  name: material
  language: ar
  direction: rtl
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: الوضع الفاتح
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: الوضع الداكن
  font:
    text: Cairo
    code: Roboto Mono
  icon:
    logo: material/bat
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - CVE Analysis:
    - Overview: cve/index.md
    - CVE-2024-XXXX: cve/cve-2024-xxxx.md
  - Book Summaries:
    - Overview: books/index.md
    - Book Name: books/book-name.md
  - SOC Reports:
    - Overview: soc/index.md
    - Report Name: soc/report-name.md
  - CTF Writeups:
    - Overview: ctf/index.md
    - CTF Name: ctf/ctf-name.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/VampireXray
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/reem-khalid-818b83250/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/bat-cursor.js

plugins:
  - search